name: Devsecops End to End pipeline

on:
    workflow_dispatch:

jobs:
    # CI- Continous integration with security check 
    code-quality: 
        uses: ./.github/workflows/code-quality.yml


    secret-scanning:
        uses: ./.github/workflows/secret-scanning.yml

    dependencies-scan:
        uses: ./.github/workflows/dependencies-scan.yml

    docker-scan:
        uses: ./.github/workflows/docker-lint.yml
    
        # Build once security scans are complete
    build:
        needs: [code-quality, secret-scanning, dependencies-scan, docker-scan]
        uses: ./.github/workflows/docker-build-push.yml
        secrets: inherit

    trivy:
        needs: [build]
        uses: ./.github/workflows/image-scan.yml
        secrets: inherit

    
    
